import { Client } from './@types/clients';
import { Server } from './@types/servers';

export const clients: Client[] = [
  {
    id: 1,
    name: "Cliente 01",
    company: "4net",
    routePlan: "Vermelho",
    fixedPlan: "Movel",
    server: "Athena",
    manager: "Barbara",
    status: "Ativo",
  },
  {
    id: 2,
    name: "Cliente 02",
    company: "Oncall",
    routePlan: "Roxo",
    fixedPlan: "Movel",
    server: "Gandalf",
    manager: "Julieth",
    status: "Bloqueado",
  },
  {
    id: 3,
    name: "Cliente 03",
    company: "Tech Solutions",
    routePlan: "Azul",
    fixedPlan: "Fixo",
    server: "Zeus",
    manager: "Carlos",
    status: "Ativo",
  },
  {
    id: 4,
    name: "Cliente 04",
    company: "Global Innovations",
    routePlan: "Verde",
    fixedPlan: "Movel",
    server: "Hades",
    manager: "Diana",
    status: "Ativo",
  },
  {
    id: 5,
    name: "Cliente 05",
    company: "Future Systems",
    routePlan: "Amarelo",
    fixedPlan: "Movel",
    server: "Apollo",
    manager: "Eduardo",
    status: "Bloqueado",
  },
  {
    id: 6,
    name: "Cliente 06",
    company: "Digital Edge",
    routePlan: "Laranja",
    fixedPlan: "Fixo",
    server: "Hera",
    manager: "Fernanda",
    status: "Ativo",
  },
  {
    id: 7,
    name: "Cliente 07",
    company: "Innovate Corp",
    routePlan: "Branco",
    fixedPlan: "Movel",
    server: "Poseidon",
    manager: "Gustavo",
    status: "Bloqueado",
  },
  {
    id: 8,
    name: "Cliente 08",
    company: "Synergy Group",
    routePlan: "Preto",
    fixedPlan: "Fixo",
    server: "Demeter",
    manager: "Helena",
    status: "Ativo",
  },
  {
    id: 9,
    name: "Cliente 09",
    company: "Quantum Tech",
    routePlan: "Cinza",
    fixedPlan: "Movel",
    server: "Hermes",
    manager: "Igor",
    status: "Ativo",
  },
  {
    id: 10,
    name: "Cliente 10",
    company: "Apex Solutions",
    routePlan: "Ciano",
    fixedPlan: "Fixo",
    server: "Artemis",
    manager: "Joana",
    status: "Bloqueado",
  },
  {
    id: 11,
    name: "Cliente 11",
    company: "Evolve Innovations",
    routePlan: "Magenta",
    fixedPlan: "Movel",
    server: "Dionysus",
    manager: "Kleber",
    status: "Ativo",
  },
  {
    id: 12,
    name: "Cliente 12",
    company: "NextGen Systems",
    routePlan: "Rosa",
    fixedPlan: "Fixo",
    server: "Ares",
    manager: "Laura",
    status: "Bloqueado",
  },
  {
    id: 13,
    name: "Cliente 13",
    company: "Pioneer Corp",
    routePlan: "Roxo Claro",
    fixedPlan: "Movel",
    server: "Hefesto",
    manager: "Marcelo",
    status: "Ativo",
  },
  {
    id: 14,
    name: "Cliente 14",
    company: "Streamline Tech",
    routePlan: "Verde Água",
    fixedPlan: "Fixo",
    server: "Afrodite",
    manager: "Natalia",
    status: "Ativo",
  },
  {
    id: 15,
    name: "Cliente 15",
    company: "Ultimate Solutions",
    routePlan: "Marrom",
    fixedPlan: "Movel",
    server: "Hecate",
    manager: "Otavio",
    status: "Bloqueado",
  },
  {
    id: 16,
    name: "Cliente 16",
    company: "Visionary Group",
    routePlan: "Bege",
    fixedPlan: "Fixo",
    server: "Eros",
    manager: "Patricia",
    status: "Ativo",
  },
  {
    id: 17,
    name: "Cliente 17",
    company: "WebWorks",
    routePlan: "Violeta",
    fixedPlan: "Movel",
    server: "Nemesis",
    manager: "Quirino",
    status: "Bloqueado",
  },
  {
    id: 18,
    name: "Cliente 18",
    company: "Xtreme Tech",
    routePlan: "Dourado",
    fixedPlan: "Fixo",
    server: "Morpheus",
    manager: "Roberta",
    status: "Ativo",
  },
  {
    id: 19,
    name: "Cliente 19",
    company: "Yield Systems",
    routePlan: "Prata",
    fixedPlan: "Movel",
    server: "Hypnos",
    manager: "Sergio",
    status: "Ativo",
  },
  {
    id: 20,
    name: "Cliente 20",
    company: "Zenith Innovations",
    routePlan: "Bronze",
    fixedPlan: "Fixo",
    server: "Nyx",
    manager: "Tatiana",
    status: "Bloqueado",
  },
  {
    id: 21,
    name: "Cliente 21",
    company: "Bright Minds",
    routePlan: "Carmesim",
    fixedPlan: "Movel",
    server: "Chronos",
    manager: "Ursula",
    status: "Ativo",
  },
  {
    id: 22,
    name: "Cliente 22",
    company: "Dynamic Solutions",
    routePlan: "Turquesa",
    fixedPlan: "Fixo",
    server: "Rhea",
    manager: "Vitor",
    status: "Bloqueado",
  },
  {
    id: 23,
    name: "Cliente 23",
    company: "Dynamic Solutions",
    routePlan: "Turquesa",
    fixedPlan: "Fixo",
    server: "Rhea",
    manager: "Vitor",
    status: "Bloqueado",
  },
  {
    id: 24,
    name: "Cliente 24",
    company: "Dynamic Solutions",
    routePlan: "Turquesa",
    fixedPlan: "Fixo",
    server: "Rhea",
    manager: "Vitor",
    status: "Bloqueado",
  },
  {
    id: 25,
    name: "Cliente 25",
    company: "Dynamic Solutions",
    routePlan: "Turquesa",
    fixedPlan: "Fixo",
    server: "Rhea",
    manager: "Vitor",
    status: "Bloqueado",
  },
];

export const servers: Server[] = [
  { id: 1, name: "Athena", ip: 192837465, totalClients: 5, status: 'Funcionando' },
  { id: 2, name: "Gandalf", ip: 192837466, totalClients: 3, status: 'Funcionando' },
  { id: 3, name: "Zeus", ip: 192837467, totalClients: 8, status: 'Inoperante' },
  { id: 4, name: "Hades", ip: 192837468, totalClients: 6, status: 'Funcionando' },
  { id: 5, name: "Apollo", ip: 192837469, totalClients: 4, status: 'Inoperante' },
  { id: 6, name: "Hera", ip: 192837470, totalClients: 7, status: 'Funcionando' },
  { id: 7, name: "Poseidon", ip: 192837471, totalClients: 2, status: 'Funcionando' },
  { id: 8, name: "Demeter", ip: 192837472, totalClients: 9, status: 'Funcionando' },
  { id: 9, name: "Hermes", ip: 192837473, totalClients: 52, status: 'Funcionando' },
  { id: 10, name: "Artemis", ip: 192837474, totalClients: 3, status: 'Inoperante' },
  { id: 11, name: "Dionysus", ip: 192837475, totalClients: 6, status: 'Funcionando' },
  { id: 12, name: "Ares", ip: 192837476, totalClients: 4, status: 'Inoperante' },
  { id: 13, name: "Hefesto", ip: 192837477, totalClients: 7, status: 'Funcionando' },
  { id: 14, name: "Afrodite", ip: 192837478, totalClients: 2, status: 'Funcionando' },
  { id: 15, name: "Hecate", ip: 192837479, totalClients: 8, status: 'Inoperante' },
  { id: 16, name: "Eros", ip: 192837480, totalClients: 5, status: 'Funcionando' },
  { id: 17, name: "Nemesis", ip: 192837481, totalClients: 3, status: 'Inoperante' },
  { id: 18, name: "Morpheus", ip: 192837482, totalClients: 6, status: 'Funcionando' },
  { id: 19, name: "Hypnos", ip: 192837483, totalClients: 4, status: 'Funcionando' },
  { id: 20, name: "Nyx", ip: 192837484, totalClients: 7, status: 'Inoperante' },
];